import type { QuestionCategory } from '@shared/types';

/** Curated starter bank (original wording). Users can add their own; seeded items cannot be deleted, only favourited. */
export const SEED_QUESTIONS: Record<QuestionCategory, string[]> = {
  hr: [
    'Tell me about yourself.',
    'Walk me through your résumé.',
    'Why do you want to work here?',
    'Why are you leaving your current role?',
    'What are your greatest strengths?',
    'What is a weakness you are actively working on?',
    'Where do you see yourself in five years?',
    'Why should we hire you over other candidates?',
    'What motivates you at work?',
    'What kind of work environment helps you do your best work?',
    'What are your salary expectations?',
    'How do you handle feedback you disagree with?',
  ],
  behavioral: [
    'Tell me about a time you failed. What did you learn?',
    'Describe a time you disagreed with your manager. How did you handle it?',
    'Give an example of a time you went above and beyond for a customer.',
    'Tell me about a time you had to meet a very tight deadline.',
    'Describe a situation where you had to learn something quickly.',
    'Tell me about a time you made a mistake at work and how you dealt with it.',
    'Describe a time you had to work with a difficult colleague.',
    'Tell me about a time you took initiative without being asked.',
    'Give an example of a time you handled competing priorities.',
    'Describe a time you received tough feedback. What did you do next?',
    'Tell me about a time you improved a process.',
    'Tell me about your proudest professional achievement.',
  ],
  leadership: [
    'Tell me about a time you led a team through a difficult change.',
    'How do you motivate a team member who is underperforming?',
    'Describe how you have developed someone on your team.',
    'Tell me about a time you had to influence people who did not report to you.',
    'How do you delegate, and how do you decide what not to delegate?',
    'Describe a decision you made that was unpopular with your team.',
    'How do you build trust with a new team?',
    'Tell me about a time you had to give difficult feedback.',
    'How do you handle conflict between two team members?',
    'What is your leadership style, and how has it changed over time?',
  ],
  management: [
    'How do you prioritise work across a team when everything is urgent?',
    'How do you set and track goals for your team?',
    'Describe how you run one-to-ones.',
    'How do you manage performance and hold people accountable?',
    'Tell me about a time you had to manage a budget or a cost target.',
    'How do you plan capacity and staffing for peak periods?',
    'How do you communicate bad news to senior leadership?',
    'Describe how you onboard a new hire so they become productive quickly.',
    'How do you make sure quality does not drop when volume rises?',
    'Tell me about a process you owned end to end.',
  ],
  technical: [
    'Walk me through a technical problem you solved recently.',
    'How do you approach debugging something you have never seen before?',
    'Explain a complex technical topic to a non-technical stakeholder.',
    'How do you decide between building a solution and buying one?',
    'How do you make sure your work is reliable and maintainable?',
    'Describe a time you had to learn a new tool or technology under pressure.',
    'How do you document your work so others can pick it up?',
    'What is your approach to testing and validating your work?',
  ],
  analytics: [
    'Walk me through how you would investigate a sudden drop in a key metric.',
    'How do you decide which KPIs matter for a team?',
    'Tell me about a time your analysis changed a decision.',
    'How do you present data to people who are not comfortable with numbers?',
    'How do you check data quality before you trust a result?',
    'Explain the difference between correlation and causation with an example.',
    'How would you design a dashboard for daily operations?',
    'Describe how you would set up and read an A/B test.',
    'Which metrics would you track to measure customer support quality?',
    'Tell me about a time the data contradicted your intuition.',
  ],
  operations: [
    'Tell me about a time you reduced cost or waste in an operation.',
    'How do you identify the bottleneck in a process?',
    'Describe how you manage service levels when demand spikes.',
    'How do you build a process that still works when you are not there?',
    'Tell me about a time you handled a major operational incident.',
    'How do you balance speed, cost and quality?',
    'What does a good escalation process look like?',
    'How do you forecast workload and plan resources?',
    'Describe how you have used root-cause analysis.',
    'How do you work with vendors and partners to hit your targets?',
  ],
  'customer-service': [
    'Tell me about a time you turned around an angry customer.',
    'How do you handle a customer request you cannot fulfil?',
    'What does great customer service mean to you?',
    'How do you stay calm and empathetic on a difficult call or chat?',
    'Describe a time you spotted a recurring customer problem and fixed the cause.',
    'How do you balance handling time with quality of service?',
    'Tell me about a time you escalated an issue appropriately.',
    'How would you handle a customer who publicly complains about us?',
    'How do you measure customer satisfaction and act on it?',
    'Give an example of a time you said no to a customer well.',
  ],
  sales: [
    'Walk me through your sales process from first contact to close.',
    'Tell me about a deal you lost and what you learned.',
    'How do you handle price objections?',
    'How do you build a pipeline when starting from zero?',
    'Describe how you prepare for a discovery call.',
    'Tell me about your biggest deal and how you closed it.',
    'How do you qualify a lead?',
    'How do you keep a long sales cycle moving?',
    'How do you work with customer success after closing a deal?',
    'What metrics do you use to manage your own performance?',
  ],
  product: [
    'How do you decide what to build next?',
    'Tell me about a product decision you made with incomplete data.',
    'How do you work with engineering when priorities conflict?',
    'How do you define success for a new feature?',
    'Describe a time you said no to a stakeholder request.',
    'How do you gather and use customer feedback?',
    'Walk me through how you would improve an app you use every day.',
    'How do you write requirements that engineers can act on?',
  ],
  finance: [
    'Walk me through the three financial statements and how they connect.',
    'How would you analyse a company’s profitability?',
    'Tell me about a time you found an error in a financial model.',
    'How do you build a forecast, and how do you check its assumptions?',
    'Explain working capital to a non-finance manager.',
    'Describe how you would present a variance analysis to leadership.',
    'How do you prioritise during month-end close?',
    'What controls would you put in place to reduce reporting errors?',
  ],
  marketing: [
    'How would you launch a product with a small budget?',
    'How do you measure the return on a marketing campaign?',
    'Tell me about a campaign that did not work and what you changed.',
    'How do you decide which channels to invest in?',
    'How do you segment an audience?',
    'Describe how you work with sales to improve lead quality.',
    'How do you build a brand voice that stays consistent?',
    'Which metrics matter most in the funnel, and why?',
  ],
  software: [
    'Describe a system you designed or worked on and the trade-offs you made.',
    'How do you review someone else’s code?',
    'Tell me about a production incident you helped resolve.',
    'How do you approach performance problems?',
    'Explain how you would design a URL shortener.',
    'How do you decide how much to test?',
    'What is the difference between processes and threads?',
    'How do you handle technical debt?',
    'Explain REST versus event-driven architectures.',
    'Walk me through what happens when you type a URL into a browser.',
  ],
  data: [
    'Explain the difference between an inner join and a left join.',
    'How do you handle missing or dirty data?',
    'Walk me through a data project from question to recommendation.',
    'How would you detect and handle outliers?',
    'Describe a time you automated a repetitive reporting task.',
    'How do you choose between a pivot table, SQL and a BI tool for a task?',
    'How do you validate that a dashboard is correct?',
    'Explain a model or method you have used and its limits.',
  ],
  'case-study': [
    'A key metric fell 20% last week. How would you find out why?',
    'Estimate how many support agents a company with 100,000 monthly tickets needs.',
    'A new competitor is undercutting our price. What do you do?',
    'How would you reduce delivery times by 15% without increasing cost?',
    'Design a process to cut the returns backlog in half.',
    'Should we open a second warehouse? What would you look at?',
    'How would you prioritise a list of ten improvement projects with one team?',
    'Customer satisfaction is falling while volume is stable. Walk me through your approach.',
  ],
  situational: [],
  'role-specific': [],
  'follow-up': [],
};
